name: ecommerce-chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    # API y servidor
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - python-dotenv==1.0.0

    # LangChain y sus extensiones
    - langchain>=0.1.9
    - langchain-community>=0.0.27
    - langchain-core>=0.1.27
    - langchain-text-splitters>=0.0.1
    - langchain-google-genai>=0.0.11
    
    # Vector store y embeddings
    - faiss-cpu==1.9.0
    - sentence-transformers>=2.2.2
    
    # Procesamiento de datos
    - pandas==2.1.3
    - numpy==1.26.2
    
    # Validación y tipos
    - pydantic>=2.5.2
    
    # LLM y procesamiento de texto
    - transformers
    - huggingface-hub>=0.20.0
    
    # Notebooks y visualización
    - jupyter==1.0.0
    - ipykernel==6.25.2
    - matplotlib==3.10.0
    - seaborn==0.13.2
    
    # UI
    - streamlit
    
    # Utilidades
    - requests