name: ecommerce-chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - python-dotenv==1.0.0
    - langchain>=0.1.9
    - langchain-community>=0.0.27
    - langchain-core>=0.1.27
    - langchain-text-splitters>=0.0.1
    - langchain-huggingface>=0.0.6
    - langchain-google-genai>=0.0.11
    - chromadb==0.4.18
    - sentence-transformers>=2.2.2
    - pandas==2.1.3
    - numpy==1.26.2
    - python-multipart==0.0.6
    - pydantic>=2.5.2
    - openai==1.3.5
    - tiktoken==0.5.1
    - pytest==7.4.3
    - black==23.11.0
    - isort==5.12.0
    - flake8==6.1.0
    - jupyter==1.0.0
    - ipykernel==6.25.2
    - matplotlib==3.10.0
    - seaborn==0.13.2 
    - faiss-cpu==1.9.0
    - huggingface-hub>=0.20.0
    - transformers
    - sentencepiece
    - requests
    - ollama==0.1.6
    - python-dotenv